# Generated by Django 5.0.2 on 2024-03-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('ID_no', models.IntegerField()),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.IntegerField(),
        ),
    ]
